- hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Paketlisten aktualisieren (ohne Upgrade)
      ansible.builtin.apt:
        update_cache: yes

    - name: Verfügbare Updates abfragen
      ansible.builtin.shell: |
        apt list --upgradable 2>/dev/null | tail -n +2
      register: upgrades

    - name: Kernel-Updates prüfen
      ansible.builtin.shell: |
        apt list --upgradable 2>/dev/null | grep -E 'linux-image|linux-headers' || true
      register: kernel_updates

    - name: Übersichtliche Ausgabe erzeugen
      ansible.builtin.debug:
        msg: |
          Host: {{ ansible_hostname }} ({{ inventory_hostname }})
          Verfügbare Updates:
          {% if upgrades.stdout_lines %}
          {% for pkg in upgrades.stdout_lines %}
            - {{ pkg }}
          {% endfor %}
          {% else %}
            - Keine Updates verfügbar
          {% endif %}

          Kernel Updates:
          {% if kernel_updates.stdout_lines %}
          {% for pkg in kernel_updates.stdout_lines %}
            - {{ pkg }}
          {% endfor %}
          {% else %}
            - Keine Kernel-Updates
          {% endif %}
